
font_family	FiraCode Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 11.0

scrollback_lines 5000

mouse_hide_wait 5.0

remember_window_size  no
initial_window_width  800
initial_window_height 600

hide_window_decorations yes

tab_bar_edge bottom
tab_bar_margin_width 4.0
tab_bar_margin_height 4.0 4.0
tab_bar_style powerline
tab_powerline_style round

background_opacity 0.85

kitty_mod super
map kitty_mod+f11    toggle_maximized

